
- name: Update and install nginx
  apt: pkg={{ item }}
       state=installed
       update_cache=yes
  with_items:
    - nginx

- name: Add default site
  become: yes
  template: src="default"
            dest="/etc/nginx/sites-available/default"

- name: Link index
  become: yes
  file: src=/etc/nginx/sites-available/default
        dest=/etc/nginx/sites-enabled/default
        state=link
  notify: restart nginx

- name: Add kibana testing site
  become: yes
  template: src="kibana"
            dest="/etc/nginx/sites-available/kibana"

- name: Link kibana
  become: yes
  file: src=/etc/nginx/sites-available/kibana
        dest="/etc/nginx/sites-enabled/kibana"
        state=link
  notify: restart nginx

