
- name: Update and install nginx
  apt: pkg={{ item }}
       state=installed
       update_cache=yes
  with_items:
    - nginx

- name: Add kafka-manager site
  become: yes
  template: src="kafka-manager.conf"
            dest="/etc/nginx/sites-available/kafka-manager"

- name: Link kafka-manager
  become: yes
  file: src=/etc/nginx/sites-available/kafka-manager
        dest=/etc/nginx/sites-enabled/kafka-manager
        state=link
  notify: restart nginx

- name: Add kafka-monitor site
  become: yes
  template: src="kafka-monitor.conf"
            dest="/etc/nginx/sites-available/kafka-monitor"

- name: Link kafka-monitor
  become: yes
  file: src=/etc/nginx/sites-available/kafka-monitor
        dest=/etc/nginx/sites-enabled/kafka-monitor
        state=link
  notify: restart nginx

- name: Add wiki site
  become: yes
  template: src="wiki.conf"
            dest="/etc/nginx/sites-available/wiki"

- name: Link wiki
  become: yes
  file: src=/etc/nginx/sites-available/wiki
        dest=/etc/nginx/sites-enabled/wiki
        state=link
  notify: restart nginx

- name: Add kibana testing site
  become: yes
  template: src="kibana.conf"
            dest="/etc/nginx/sites-available/kibana"

- name: Link kibana
  become: yes
  file: src=/etc/nginx/sites-available/kibana
        dest="/etc/nginx/sites-enabled/kibana"
        state=link
  notify: restart nginx
