# Copyright 2016(c) The Ontario Institute for Cancer Research. All rights reserved.

- name: Configure Cloudera APT key
  apt_key: url="http://archive.cloudera.com/cdh5/ubuntu/{{ ansible_distribution_release }}/amd64/cdh/archive.key"
           state=present

- name: Configure the Cloudera APT repositories
  apt_repository: repo="deb [arch=amd64] http://archive.cloudera.com/cdh5/ubuntu/{{ ansible_distribution_release }}/amd64/cdh {{ ansible_distribution_release }}-{{ hdfs_cloudera_distribution }} contrib"
                  state=present

- apt: update_cache=yes

- name: install native compression
  apt: name=liblzo2-dev

- name: add hostname to /etc/hosts
  # needed for host IP resolution, because DNS is not installed in exastack
  # TODO: get host info from group variable.  See
  # http://docs.ansible.com/ansible/playbooks_variables.html#magic-variables-and-how-to-access-information-about-other-hosts
  lineinfile:
    dest: /etc/hosts
    line: "{{ hostvars[lookup('inventory_hostnames', item )].openstack.private_v4 }} {{ item }}"
  with_items: # this list duplicates the host list in the top level, so should be in a variable.
    - dcc-hdfs-namenode
    - dcc-spark-worker-1
    - dcc-spark-worker-2
    - dcc-spark-worker-3
    - dcc-spark-worker-4
    - dcc-spark-worker-5
    - dcc-spark-worker-6
    - dcc-spark-worker-7
    - dcc-spark-worker-8
    - dcc-spark-worker-9
    - dcc-spark-worker-10

- { include: datanode.yml, when: not hdfs_namenode }
- { include: namenode.yml, when: hdfs_namenode }

