# Copyright 2016(c) The Ontario Institute for Cancer Research. All rights reserved.

- name: Configure Cloudera APT key
  apt_key: url="http://archive.cloudera.com/cdh5/ubuntu/{{ ansible_distribution_release }}/amd64/cdh/archive.key"
           state=present

- name: Configure the Cloudera APT repositories
  apt_repository: repo="deb [arch=amd64] http://archive.cloudera.com/cdh5/ubuntu/{{ ansible_distribution_release }}/amd64/cdh {{ ansible_distribution_release }}-{{ hdfs_cloudera_distribution }} contrib"
                  state=present

- apt: update_cache=yes

- name: install native compression
  apt: name=liblzo2-dev

- name: add HDFS datanode hostnames to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "{{ item }}"
    line: "{{ hostvars[lookup('inventory_hostnames', item )].openstack.private_v4 }} {{ item }}"
  with_items: "{{ groups['dcc_spark_workers'] }}"

- name: add HDFS master to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "dcc-etl-2"
    line: "{{ hostvars[lookup('inventory_hostnames', 'dcc-etl-2' )].openstack.private_v4 }} dcc-etl-2"

- { include: datanode.yml, when: not hdfs_namenode }
- { include: namenode.yml, when: hdfs_namenode }

