# Copyright 2016(c) The Ontario Institute for Cancer Research. All rights reserved.

- name: Configure Cloudera APT key
  apt_key: url="http://archive.cloudera.com/cdh5/ubuntu/{{ ansible_distribution_release }}/amd64/cdh/archive.key"
           state=present

- name: Configure the Cloudera APT repositories
  apt_repository: repo="deb [arch=amd64] http://archive.cloudera.com/cdh5/ubuntu/{{ ansible_distribution_release }}/amd64/cdh {{ ansible_distribution_release }}-{{ hdfs_cloudera_distribution }} contrib"
                  state=present

- apt: update_cache=yes

- name: install native compression
  apt: name=liblzo2-dev

- name: add hostname to /etc/hosts
  # needed for host IP resolution, because DNS is not installed in exastack
  lineinfile:
    dest: /etc/hosts
    line: "{{ hostvars[lookup('inventory_hostnames', item )].openstack.private_v4 }} {{ item }}"
  with_items: [dcc-hdfs-namenode, dcc-hdfs-datanode-1, dcc-hdfs-datanode-2] # this list duplicates the host list in the top level, so should be in a variable.

- { include: namenode.yml, when: hdfs_namenode }
- { include: datanode.yml, when: not hdfs_namenode }

