# https://github.com/elastic/ansible-elasticsearch
# https://github.com/geerlingguy/ansible-role-kibana
- name: Elasticsearch with custom configuration
  hosts: dcc-es-1, dcc-es-2, dcc-es-3
  remote_user: ubuntu
  become: true
  roles:
    - java
    - { role: elasticsearch, 
        es_major_version: "1.4",
        es_version: "1.4.4",
        es_instance_name: "{{ ansible_hostname }}", es_data_dirs:
      "/opt/elasticsearch/data", es_log_dir: "/opt/elasticsearch/logs", es_work_dir: "/opt/elasticsearch/temp", 
      es_config: {
        node.name: "{{ ansible_hostname }}", 
        cluster.name: "elasticsearch",
        script.disable_dynamic: false # enable groovy
      }
    }
  vars:
    es_java_install: false
    # plugin install by this role doesn't work for ES 1.4.4
  tasks:
  - name: install plugin
    command: /usr/share/elasticsearch/bin/plugin --install mobz/elasticsearch-head/1.x
    ignore_errors: true # this task fails if the plugin is already installed, so we ignore errors for repeatability 
- name: Kibana monitor
  hosts: monitor
  remote_user: ubuntu
  become: true
  roles:
    - java
    - { role: kibana,
        kibana_version: "4.1", 
        kibana_elasticsearch_url: "{{ kibana_elasticsearch_url }}" # e.g. "http://tempuri.org:9200"
      }
