# Copyright 2016(c) The Ontario Institute for Cancer Research. All rights reserved.


# Spark master and HDFS namenode
- hosts: dcc-etl-2
  remote_user: ubuntu
  become: yes
  vars_files:
    - "vars/main.yml"
  roles:
    - jdk
    - { role: spark, master: True }
    - { role: hdfs, hdfs_namenode: True}
    - rsyslog-elasticsearch

# Spark workers and HDFS data nodes
- hosts: dcc_spark_workers
  remote_user: ubuntu
  become: yes
  vars_files:
    - "vars/main.yml"
  roles:
    - jdk
    - { role: spark, master: False}
    - { role: hdfs, hdfs_namenode: False}

