# Copyright 2016(c) The Ontario Institute for Cancer Research. All rights reserved.


# Spark - Master
- hosts: dcc-etl-2
  remote_user: ubuntu
  become: yes
  vars_files:
    - "vars/main.yml"
  roles:
    - jdk
    - { role: spark, master: True }

# Spark workers
- hosts: dcc_spark_workers
  remote_user: ubuntu
  become: yes
  vars_files:
    - "vars/main.yml"
  roles:
    - jdk
    - { role: spark, master: False}

# HDFS
- hosts: dcc-hdfs-namenode
  remote_user: ubuntu
  become: yes
  vars_files:
    - "vars/main.yml"
  roles:
    - { role: hdfs, hdfs_namenode: True}

- hosts: dcc-hdfs-datanode-1, dcc-hdfs-datanode-2
  remote_user: ubuntu
  become: yes
  vars_files:
    - "vars/main.yml"
  roles:
    - { role: hdfs, hdfs_namenode: False}
