# Copyright 2016(c) The Ontario Institute for Cancer Research. All rights reserved.


# Spark - Master
- hosts: dcc-etl-2
  remote_user: ubuntu
  become: yes
  vars_files:
    - "vars/main.yml"
  roles:
    # - jdk already installed
    - { role: spark, master: True }

# Spark - Slave
- hosts: dcc-spark-worker-1, dcc-spark-worker-2, dcc-spark-worker-3, dcc-spark-worker-4
  remote_user: ubuntu
  become: yes
  vars_files:
    - "vars/main.yml"
  roles:
    - jdk
    - { role: spark, master: False}

# HDFS
- hosts: dcc-hdfs-namenode
  remote_user: ubuntu
  become: yes
  vars_files:
    - "vars/main.yml"
  roles:
    - { role: hdfs, hdfs_namenode: True}

- hosts: dcc-hdfs-datanode-1, dcc-hdfs-datanode-2
  remote_user: ubuntu
  become: yes
  vars_files:
    - "vars/main.yml"
  roles: 
    - { role: hdfs, hdfs_namenode: False}
