
# monitor services in the OpenStack project
- hosts: monitor
  remote_user: ubuntu
  become: yes
  vars_files:
    - "vars/main.yml"
  roles:
    - jdk
    - { role: elasticsearch, 
        es_major_version: "5.x",
        es_version: "5.2.0",
        es_instance_name: "{{ ansible_hostname }}", es_data_dirs:
      "/opt/elasticsearch/data", es_log_dir: "/opt/elasticsearch/logs", es_work_dir: "/opt/elasticsearch/temp", 
      es_config: {
          node.name: "{{ ansible_hostname }}", 
          cluster.name: "monitor-es"
        }
      }
    - { role: kibana,
        kibana_elasticsearch_url: "http://localhost:9200", # e.g. "http://tempuri.org:9200"
        kibana_server_host: "{{ ansible_default_ipv4.address }}"
      }
    - rsyslog-elasticsearch
  vars:
    es_java_install: false
  tasks:
  - name: install plugin
    command: /usr/share/elasticsearch/bin/plugin --install mobz/elasticsearch-head/1.x
    ignore_errors: true # this task fails if the plugin is already installed, so we ignore errors for repeatability 

# kafka will need a certificate for TLS
# keytool -keystore roles/kafka-security/files/kafka.keystore.jks -alias
# localhost -validity 365 -genkey
- hosts: kafka 
  remote_user: ubuntu
  become: yes
  roles:
    - jdk
    - role: AnsibleShipyard.ansible-zookeeper
      zookeeper_hosts:
        - host: kafka
          id: 1 
    - role: ansible-kafka
      kafka_hosts: [kafka]
      kafka_zookeeper_hosts: [kafka]
      healthcheck_address: kafka
