---
- hosts: kafka 
  remote_user: ubuntu
  become: yes
  roles:
    - jdk
    - role: AnsibleShipyard.ansible-zookeeper
      zookeeper_hosts:
        - host: kafka
          id: 1 
    - role: ansible-kafka
      kafka_hosts: [kafka]
      kafka_zookeeper_hosts: [kafka]
      healthcheck_address: kafka
    # kafka-manage may take 10-15 minutes to install, because the Scala sbt
    # build downloads many JVM libraries.
    - kafka-manager
