# Copyright 2016(c) The Ontario Institute for Cancer Research. All rights reserved.

- name: Start Spark Master
  become: yes
  shell: "/srv/{{ spark_archive_output }}/sbin/start-master.sh"
  when: master

- name: Start Spark Slave
  become: yes
  shell: "/srv/{{ spark_archive_output }}/sbin/start-slave.sh spark://10.60.60.55:7077"
  when: not master
