
- name: Install NPM
  apt: pkg={{ item }}
       state=installed
       update_cache=yes
  with_items:
    - build-essential
    - python-dev
    - nodejs
    - npm
    - nodejs-legacy
    - python-pip
    - uwsgi-plugin-python

- name: Install bower
  npm: name=bower global=yes

- name: Install virtualenv
  pip: name=virtualenv

#- name: Install uwsgi
#  pip: name=uwsgi
#       virtualenv=/mnt/git/kafka-simple-monitor
#       virtualenv_python=python2.7

- name: Set kafka-monitor ownership to ubuntu
  file: path=/mnt/git/kafka-simple-monitor 
        owner=ubuntu 
        group=ubuntu
        recurse=yes

- name: Configure waf
  command: ./waf configure chdir=/mnt/git/kafka-simple-monitor/

- name: Build waf
  become: no
  command: ./waf build chdir=/mnt/git/kafka-simple-monitor/
