
- name: Install NPM
  apt: pkg={{ item }}
       state=installed
       update_cache=yes
  with_items:
    - nodejs
    - npm
    - nodejs-legacy

- name: Install bower
  npm: name=bower global=yes

#- name: Point to node executable
#  command: ln -s /usr/bin/nodejs /usr/bin/node

- name: Configure waf
  command: ./waf configure chdir=/mnt/git/kafka-simple-monitor/

- name: Build waf
  command: ./waf build chdir=/mnt/git/kafka-simple-monitor/
