
- name: Need SSH key
  become: yes
  copy: src=~/.ssh/cdgroup.pem 
        dest=~/.ssh/cdgroup.pem
        owner=root
        group=root
        mode=0644

- name: Download main portal repos
  git: repo=ubuntu@10.96.11.127:/mnt/git/portal_html.git
       dest=/mnt/git/
       key_file=~/.ssh/cdgroup.pem
