
- name: Install git
  become: yes
  apt: pkg={{ item }}
       state=installed
       update_cache=yes
  with_items:
    - git

- name: Need SSH key
  become: yes
  copy: src=~/.ssh/cdgroup.pem 
        dest=~/.ssh/cdgroup.pem
        owner=root
        group=root
        mode=0644

- name: Download main portal repos
  become: yes
  git: repo=ubuntu@10.60.60.103:/mnt/git/portal_html.git
       dest=/mnt/git/
       key_file=~/.ssh/cdgroup.pem
