# Copyright 2016(c) The Ontario Institute for Cancer Research. All rights reserved.

- name: add compression library for HDFS
  apt: name=liblzo2-dev

- name: Ensure directories
  file: path={{ item }} state=directory
  with_items:
    - "{{ install_dir }}"

- name: Download the distribution
  get_url:  url="{{ spark_artifactory }}"
            dest="{{ install_dir }}/"
            mode=0444

- name: Extract the dist
  unarchive:
    src: "{{ install_dir }}/{{ spark_archive }}"
    dest: "{{ install_dir }}"
    copy: no

- name: configure the logger
  template:
    src: log4j.properties.j2
    dest: "{{ spark_conf_dir }}/log4j.properties"

- name: add hostname to /etc/hosts
  # needed for host IP resolution, because DNS is not installed in exastack
  lineinfile:
    dest: /etc/hosts
    line: '{{ ansible_default_ipv4.address }} {{ ansible_hostname }}'

- name: add names of other members of cluster to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "dcc-spark-worker-{{ item }}"
    line: "{{ hostvars[lookup('inventory_hostnames', item )].openstack.private_v4 }} {{ item }}"
  with_items: "{{ groups['dcc_spark_workers'] }}"

- { include: master.yml, when: master }
- { include: worker.yml, when: not master }
