# Copyright 2016(c) The Ontario Institute for Cancer Research. All rights reserved.

- name: Clean copy
  file: 
    path: "{{ install_dir }}"
    state: absent

- name: Ensure directories
  file: path={{ item }} state=directory
  with_items:
    - "{{ install_dir }}"

- name: Download the distribution
  get_url:  url="{{ spark_artifactory }}"
            dest="{{ install_dir }}/"
            mode=0444

- name: Extract the dist
  unarchive:  
    src: "{{ install_dir }}/{{ spark_archive }}"
    dest: "{{ install_dir }}"
    copy: no

- name: configure the logger
  template:
    src: log4j.properties.j2
    dest: "{{ spark_conf_dir }}/log4j.properties"

- name: add hostname to /etc/hosts
  # needed for host IP resolution, because DNS is not installed in exastack
  lineinfile:
    dest: /etc/hosts
    line: '{{ ansible_default_ipv4.address }} {{ ansible_hostname }}'

- { include: master.yml, when: master }
- { include: worker.yml, when: not master }
