- name: Configure Spark Worker 
  template: src=spark-defaults.conf.j2 dest=/srv/{{ spark_archive_output }}/conf/spark-defaults.conf

- name: Configure Spark Worker
  template: src=spark-env.sh.j2 dest=/srv/{{ spark_archive_output }}/conf/spark-env.sh mode="u=rwx,g=r,o=r"
  notify:
    - Start Spark Slave
