---

- name: prep euler
  file: path=/opt/server state=directory owner=ubuntu group=ubuntu

#- name: ensure github is a known host
#  action: sshknownhosts host=github.com state=present 

- name: git euler
  become_user: ubuntu
  git:
    repo=https://github.com/ohsu-comp-bio/euler
    version=nginx
    dest=/opt/server/euler
    accept_hostkey=yes
    recursive=yes
    force=yes

- name: configure euler
  # see vars/main.yml
  template:
    src: env.j2
    dest: /opt/server/euler/.env
    owner: ubuntu
    group: ubuntu
 
- name: start euler
  become_user: ubuntu
  command: docker-compose -f docker-compose.yml -f docker-compose-openstack.yml -f docker-compose-dcc.yml up -d 
  args:
    chdir: /opt/server/euler
 
