
- shell: dpkg -s linux-headers-generic-lts-vivid  
  ignore_errors: True
  register: dpkg_result

- debug:
    msg: "dpkg_result {{ dpkg_result }}"


- name: kernel update | Install latest kernel
  apt: name={{item}} state=present update_cache=yes
  with_items:
       - linux-generic-lts-vivid
       - linux-headers-generic-lts-vivid
  register: kernel_update
  when: dpkg_result | failed

- name: kernel update | Reboot now
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  when: kernel_update | changed 

- name: waiting 30 secs for server to come back
  local_action: wait_for host={{ ansible_default_ipv4.address }} port=22 state=started delay=30 timeout=60
  become: false
  when: kernel_update | changed 

- name: kernel update | pause a little to ensure everything is running
  pause:
    seconds="5"
  when: kernel_update | changed 

