
- name: Install items
  apt: pkg={{ item }}
       state=installed
       update_cache=yes
  with_items:
    - unzip

- name: Ensure directory exists
  file: path=/mnt/dist/ state=directory

- name: Download kafka-manager tarball
  get_url: url=https://github.com/yahoo/kafka-manager/archive/1.3.1.6.tar.gz
           dest=/mnt/dist/

- name: Unarchive the dist
  unarchive: src=/mnt/dist/kafka-manager-1.3.1.6.tar.gz
             dest=/mnt/dist
             copy=no

- name: Rename dist file
  command: mv kafka-manager-1.3.1.6 kafka-manager-tar 
           chdir=/mnt/dist
           creates=./kafka-manager-tar

- name: Make bin
  command: ./sbt clean dist 
           chdir=/mnt/dist/kafka-manager-tar
           creates=./target/universal/kafka-manager-1.3.1.6.zip

- name: Grab bin
  copy: remote_src=True
        src=/mnt/dist/kafka-manager-tar/target/universal/kafka-manager-1.3.1.6.zip
        dest=/mnt/dist/

- name: Unzip dist
  unarchive: src=/mnt/dist/kafka-manager-1.3.1.6.zip
             dest=/mnt/dist
             copy=no

#- name: Unzip dist
#  command: unzip kafka-manager-1.3.1.6.zip chdir=/mnt/dist

- name: Make a sym link
  file: src=/mnt/dist/kafka-manager-1.3.1.6
        dest=/mnt/dist/kafka-manager
        state=link
